export const createChurchAndUserRules = {
  churchName: "required|string",
  churchType: "required|string",
  email: "required|string",
  phoneNumber: "required|min:11|max:13|phone",
  website: "required|string",
  streetAddress: "required|string",
  city: "required|string",
  stateRegion: "required|string",
  country: "required|string",
  timeZone: "required|string",
  baseCurrency: "required|string",
  fiscalYearStart: "required|date",
  digitalGivingAndDonations: "boolean",
  expenseManagement: "boolean",
  payrollManagement: "boolean",
  memberManagement: "boolean",
  digitalGiving: "boolean",
  eventsAndCheckIn: "boolean",
  smallGroups: "boolean",
  volunteerManagement: "boolean",
  communications: "boolean",
  facilities: "boolean",
  mediaLibrary: "boolean",

  userFirstName: "required|string",
  userLastName: "required|string",
  userEmail: "required|string",
  userPassword: "required|string",
  userRole: "required|string",
};
