export type CreateChurchAndUser = {
  churchName: string;
  churchType: string;
  email: string;
  phoneNumber: string;
  website: string | null;
  streetAddress: string;
  city: string;
  stateRegion: string;
  country: string;
  timeZone: string;
  baseCurrency: string;
  fiscalYearStart: Date;
  initialFundsToCreate: string[];
  digitalGivingAndDonations: boolean;
  expenseManagement: boolean;
  payrollManagement: boolean;
  memberManagement: boolean;
  digitalGiving: boolean;
  eventsAndCheckIn: boolean;
  smallGroups: boolean;
  volunteerManagement: boolean;
  communications: boolean;
  facilities: boolean;
  mediaLibrary: boolean;

  userFirstName?: string;
  userLastName?: string;
  userEmail?: string;
  userPassword?: string;
  userRole?: string;
  churchId?: string;
};
