export const addMemberRules = {
  firstName: "required|string",
  lastName: "required|string",
  middleName: "string",
  email: "required|string|email",
  phoneNumber: "required|min:11|max:13|phone",
  dateOfBirth: "string",
  gender: "string",
  maritalStatus: "string",
  occupation: "string",
  streetAddress: "string",
  city: "string",
  state: "string",
  country: "string",
  contactName: "string",
  contactNumber: "string",
  relationship: "string",
  membershipStatus: "string",
  joinDate: "date",
  baptismDate: "date",
  notes: "string",
  avatar: "string",
};
