export const updateMemberRules = {
  firstName: "string",
  lastName: "string",
  middleName: "string",
  phoneNumber: "min:11|max:13|phone",
  dateOfBirth: "string",
  maritalStatus: "string",
  occupation: "string",
  streetAddress: "string",
  city: "string",
  state: "string",
  country: "string",
  contactName: "string",
  contactNumber: "string",
  relationship: "string",
  membershipStatus: "string",
  joinDate: "date",
  baptismDate: "date",
  campusId: "string",
};
