export enum AccessControls {
	USER_ONBOARDING = "add-member",
	BULK_USER_ONBOARDING = "bulk_user_onboarding",
	USER_LIST = "view-members",
	USER_ACCOUNT_DEACTIVATION = "user_account_deactivation",
	USER_ACCOUNT_REACTIVATION = "user_account_reactivation",
	USER_PROFILE_UPDATE = "edit-member",
	USER_PASSWORD_RESET = "user_password_reset",
	ROLE_CREATION = "role_creation",
	ROLE_LIST = "role_list",
	ROLE_UPDATE = "role_update",
	ROLE_DELETION = "role_deletion",
	ROLE_ASSIGNMENT = "role_assignment",
	POLICY_CREATION = "policy_creation",
	POLICY_LIST = "policy_list",
	POLICY_APPROVAL = "policy_approval",
	POLICY_REJECTION = "policy_rejection",
	PRODUCT_CREATION = "product_creation",
	PRODUCT_LIST = "product_list",
	QUOTE_CREATION = "quotes_creation",
	QUOTE_LIST = "quotes_list",
	TRANSACTION_PIN = "transaction_pin",
	WALLET = "wallet",
}
