export const createGroupRules = {
  groupName: "required|string",
  category: "required|string",
  description: "string",
  capacity: "numeric",
  meetingDay: "string",
  meetingTime: "string",
  frequency: "string",
  location: "string",
  "criterias.*.criteriaType": "string:in:age,gender,marital-status",
  "criterias.*.minAge": "numeric",
  "criterias.*.maxAge": "numeric",
  "criterias.*.sex": "string:in:Male,Female",
  "criterias.*.status": "string:in:Single,Married,Divorced,Widowed",
  publicGroup: "boolean",
  allowGuestInvites: "boolean",
  requireLeaderApproval: "boolean",
  enableGroupChat: "boolean",
};
