export const recordAttendanceRules = {
  meetingDate: "required|string",
  guestCount: "required",
  attended: "numeric",
  absent: "numeric",
  excused: "numeric",
  guestNames: "array",
  presentMembers: "array",
  absentMembers: "array",
  excusedMembers: "array",
  meetingTopic: "required|string",
  meetingNotes: "string",
  testimonies: "string",
  prayerRequests: "string",
};
