import { Knex } from "knex";
import { DB_TABLES } from "../../shared/enums/db-tables.enum";

export async function seed(knex: Knex): Promise<void> {
  await knex(DB_TABLES.PERMISSIONS).del();

  // Fetch module IDs
  const modules = await knex(DB_TABLES.MODULES).select("id", "name");
  const moduleMap: Record<string, string> = {};
  modules.forEach((m) => {
    moduleMap[m.name] = m.id;
  });

  await knex(DB_TABLES.PERMISSIONS).insert([
    // ============================================
    // DASHBOARD PERMISSIONS
    // ============================================
    {
      moduleId: moduleMap["Dashboard"],
      name: "View Dashboard",
      slug: "view-dashboard",
      action: "read",
      description: "View dashboard analytics and overview",
    },
    {
      moduleId: moduleMap["Dashboard"],
      name: "Quick Add Member",
      slug: "quick-add-member",
      action: "create",
      description: "Quick add member from dashboard",
    },
    {
      moduleId: moduleMap["Dashboard"],
      name: "Quick Create Event",
      slug: "quick-create-event",
      action: "create",
      description: "Quick create event from dashboard",
    },
    {
      moduleId: moduleMap["Dashboard"],
      name: "View Recent Transactions",
      slug: "view-recent-transactions",
      action: "read",
      description: "View recent transactions widget",
    },

    // ============================================
    // COMMUNICATIONS PERMISSIONS
    // ============================================
    {
      moduleId: moduleMap["Communications"],
      name: "View Communications",
      slug: "view-communications",
      action: "read",
      description: "View all messages and announcements",
    },
    {
      moduleId: moduleMap["Communications"],
      name: "Create Communication",
      slug: "create-communication",
      action: "create",
      description: "Create new messages and announcements",
    },
    {
      moduleId: moduleMap["Communications"],
      name: "Edit Communication",
      slug: "edit-communication",
      action: "update",
      description: "Edit existing communications",
    },
    {
      moduleId: moduleMap["Communications"],
      name: "Delete Communication",
      slug: "delete-communication",
      action: "delete",
      description: "Delete communications",
    },
    {
      moduleId: moduleMap["Communications"],
      name: "Manage Campaigns",
      slug: "manage-campaigns",
      action: "manage",
      description: "Manage communication campaigns",
    },
    {
      moduleId: moduleMap["Communications"],
      name: "View Communication Analytics",
      slug: "view-communication-analytics",
      action: "read",
      description: "View communication analytics",
    },

    // ============================================
    // REPORTS PERMISSIONS
    // ============================================
    {
      moduleId: moduleMap["Reports"],
      name: "View Reports",
      slug: "view-reports",
      action: "read",
      description: "View reports module",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Generate Financial Reports",
      slug: "generate-financial-reports",
      action: "create",
      description: "Generate financial reports",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Generate Giving Reports",
      slug: "generate-giving-reports",
      action: "create",
      description: "Generate giving reports",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Generate Member Reports",
      slug: "generate-member-reports",
      action: "create",
      description: "Generate member reports",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Generate Ministry Reports",
      slug: "generate-ministry-reports",
      action: "create",
      description: "Generate ministry reports",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Generate Payroll Reports",
      slug: "generate-payroll-reports",
      action: "create",
      description: "Generate payroll reports",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Generate Campus Reports",
      slug: "generate-campus-reports",
      action: "create",
      description: "Generate campus reports",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Export Reports",
      slug: "export-reports",
      action: "export",
      description: "Export reports to various formats",
    },
    {
      moduleId: moduleMap["Reports"],
      name: "Create Custom Reports",
      slug: "create-custom-reports",
      action: "create",
      description: "Create custom date range reports",
    },

    // ============================================
    // PEOPLE PERMISSIONS
    // ============================================
    // Members
    {
      moduleId: moduleMap["People"],
      name: "View Members",
      slug: "view-members",
      action: "read",
      description: "View member directory",
    },
    {
      moduleId: moduleMap["People"],
      name: "Add Member",
      slug: "add-member",
      action: "create",
      description: "Add new members",
    },
    {
      moduleId: moduleMap["People"],
      name: "Edit Member",
      slug: "edit-member",
      action: "update",
      description: "Edit member information",
    },
    {
      moduleId: moduleMap["People"],
      name: "Delete Member",
      slug: "delete-member",
      action: "delete",
      description: "Delete members",
    },
    {
      moduleId: moduleMap["People"],
      name: "View Member Analytics",
      slug: "view-member-analytics",
      action: "read",
      description: "View member analytics",
    },
    {
      moduleId: moduleMap["People"],
      name: "Manage Member Status",
      slug: "manage-member-status",
      action: "manage",
      description: "Manage member status (active, inactive, visitor)",
    },
    // Family Mapper
    {
      moduleId: moduleMap["People"],
      name: "View Families",
      slug: "view-families",
      action: "read",
      description: "View family units",
    },
    {
      moduleId: moduleMap["People"],
      name: "Create Family",
      slug: "create-family",
      action: "create",
      description: "Create new family",
    },
    {
      moduleId: moduleMap["People"],
      name: "Edit Family",
      slug: "edit-family",
      action: "update",
      description: "Edit family relationships",
    },
    {
      moduleId: moduleMap["People"],
      name: "Delete Family",
      slug: "delete-family",
      action: "delete",
      description: "Delete family unit",
    },
    {
      moduleId: moduleMap["People"],
      name: "Link Members to Family",
      slug: "link-members-to-family",
      action: "update",
      description: "Link unlinked members to families",
    },
    // Engagement Scoring
    {
      moduleId: moduleMap["People"],
      name: "View Engagement Scores",
      slug: "view-engagement-scores",
      action: "read",
      description: "View engagement scores",
    },
    {
      moduleId: moduleMap["People"],
      name: "Configure Engagement Weights",
      slug: "configure-engagement-weights",
      action: "manage",
      description: "Configure engagement weights",
    },
    {
      moduleId: moduleMap["People"],
      name: "Create Follow-up Task",
      slug: "create-followup-task",
      action: "create",
      description: "Create follow-up tasks for low engagement",
    },
    {
      moduleId: moduleMap["People"],
      name: "Recalculate Engagement Scores",
      slug: "recalculate-engagement-scores",
      action: "manage",
      description: "Recalculate engagement scores",
    },
    // Staff Management
    {
      moduleId: moduleMap["People"],
      name: "View Staff",
      slug: "view-staff",
      action: "read",
      description: "View staff directory",
    },
    {
      moduleId: moduleMap["People"],
      name: "Add Staff",
      slug: "add-staff",
      action: "create",
      description: "Add new staff member",
    },
    {
      moduleId: moduleMap["People"],
      name: "Edit Staff",
      slug: "edit-staff",
      action: "update",
      description: "Edit staff information",
    },
    {
      moduleId: moduleMap["People"],
      name: "Delete Staff",
      slug: "delete-staff",
      action: "delete",
      description: "Remove staff member",
    },
    {
      moduleId: moduleMap["People"],
      name: "Manage Staff Contracts",
      slug: "manage-staff-contracts",
      action: "manage",
      description: "Manage staff contracts",
    },
    {
      moduleId: moduleMap["People"],
      name: "View Staff Credentials",
      slug: "view-staff-credentials",
      action: "read",
      description: "View staff credentials",
    },
    // Leave Management
    {
      moduleId: moduleMap["People"],
      name: "View Leave Requests",
      slug: "view-leave-requests",
      action: "read",
      description: "View leave requests",
    },
    {
      moduleId: moduleMap["People"],
      name: "Create Leave Request",
      slug: "create-leave-request",
      action: "create",
      description: "Submit leave request",
    },
    {
      moduleId: moduleMap["People"],
      name: "Approve Leave",
      slug: "approve-leave",
      action: "approve",
      description: "Approve leave requests",
    },
    {
      moduleId: moduleMap["People"],
      name: "Reject Leave",
      slug: "reject-leave",
      action: "reject",
      description: "Reject leave requests",
    },
    {
      moduleId: moduleMap["People"],
      name: "View Leave Balances",
      slug: "view-leave-balances",
      action: "read",
      description: "View leave balances",
    },
    // Performance Appraisals
    {
      moduleId: moduleMap["People"],
      name: "View Performance Appraisals",
      slug: "view-performance-appraisals",
      action: "read",
      description: "View performance appraisals",
    },
    {
      moduleId: moduleMap["People"],
      name: "Create Performance Review",
      slug: "create-performance-review",
      action: "create",
      description: "Create performance review",
    },
    {
      moduleId: moduleMap["People"],
      name: "Manage Performance Goals",
      slug: "manage-performance-goals",
      action: "manage",
      description: "Manage performance goals",
    },
    {
      moduleId: moduleMap["People"],
      name: "Submit Performance Rating",
      slug: "submit-performance-rating",
      action: "create",
      description: "Submit performance ratings",
    },
    // Volunteer Management
    {
      moduleId: moduleMap["People"],
      name: "View Volunteers",
      slug: "view-volunteers",
      action: "read",
      description: "View volunteer directory",
    },
    {
      moduleId: moduleMap["People"],
      name: "Add Volunteer",
      slug: "add-volunteer",
      action: "create",
      description: "Add new volunteer",
    },
    {
      moduleId: moduleMap["People"],
      name: "Edit Volunteer",
      slug: "edit-volunteer",
      action: "update",
      description: "Edit volunteer information",
    },
    {
      moduleId: moduleMap["People"],
      name: "Manage Background Checks",
      slug: "manage-background-checks",
      action: "manage",
      description: "Manage background checks",
    },
    {
      moduleId: moduleMap["People"],
      name: "Track Volunteer Hours",
      slug: "track-volunteer-hours",
      action: "manage",
      description: "Track volunteer hours",
    },
    // Volunteer Schedule
    {
      moduleId: moduleMap["People"],
      name: "View Volunteer Schedule",
      slug: "view-volunteer-schedule",
      action: "read",
      description: "View volunteer schedule",
    },
    {
      moduleId: moduleMap["People"],
      name: "Create Volunteer Shift",
      slug: "create-volunteer-shift",
      action: "create",
      description: "Create volunteer shifts",
    },
    {
      moduleId: moduleMap["People"],
      name: "Assign Volunteers",
      slug: "assign-volunteers",
      action: "update",
      description: "Assign volunteers to shifts",
    },
    {
      moduleId: moduleMap["People"],
      name: "Manage Volunteer Roles",
      slug: "manage-volunteer-roles",
      action: "manage",
      description: "Manage volunteer roles",
    },
    // Volunteer Recognition
    {
      moduleId: moduleMap["People"],
      name: "View Volunteer Recognition",
      slug: "view-volunteer-recognition",
      action: "read",
      description: "View volunteer recognition",
    },
    {
      moduleId: moduleMap["People"],
      name: "Create Volunteer Award",
      slug: "create-volunteer-award",
      action: "create",
      description: "Create awards",
    },
    {
      moduleId: moduleMap["People"],
      name: "Assign Volunteer Award",
      slug: "assign-volunteer-award",
      action: "update",
      description: "Assign awards to volunteers",
    },
    {
      moduleId: moduleMap["People"],
      name: "Manage Volunteer Milestones",
      slug: "manage-volunteer-milestones",
      action: "manage",
      description: "Manage milestone levels",
    },

    // ============================================
    // MINISTRY PERMISSIONS
    // ============================================
    // Events
    {
      moduleId: moduleMap["Ministry"],
      name: "View Events",
      slug: "view-events",
      action: "read",
      description: "View all events",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Create Event",
      slug: "create-event",
      action: "create",
      description: "Create new event",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Edit Event",
      slug: "edit-event",
      action: "update",
      description: "Edit event details",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Delete Event",
      slug: "delete-event",
      action: "delete",
      description: "Delete events",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Manage Event Registration",
      slug: "manage-event-registration",
      action: "manage",
      description: "Manage event registration",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Manage Recurring Events",
      slug: "manage-recurring-events",
      action: "manage",
      description: "Manage recurring events",
    },
    // Small Groups
    {
      moduleId: moduleMap["Ministry"],
      name: "View Small Groups",
      slug: "view-small-groups",
      action: "read",
      description: "View small groups",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Create Small Group",
      slug: "create-small-group",
      action: "create",
      description: "Create new small group",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Edit Small Group",
      slug: "edit-small-group",
      action: "update",
      description: "Edit group details",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Delete Small Group",
      slug: "delete-small-group",
      action: "delete",
      description: "Delete small group",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Manage Group Members",
      slug: "manage-group-members",
      action: "manage",
      description: "Manage group members",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Assign Group Leader",
      slug: "assign-group-leader",
      action: "update",
      description: "Assign group leader",
    },
    // Discover Small Groups
    {
      moduleId: moduleMap["Ministry"],
      name: "Search Small Groups",
      slug: "search-small-groups",
      action: "read",
      description: "Search and discover groups",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Request to Join Group",
      slug: "request-to-join-group",
      action: "create",
      description: "Request to join group",
    },
    // Prayer Requests
    {
      moduleId: moduleMap["Ministry"],
      name: "View Prayer Requests",
      slug: "view-prayer-requests",
      action: "read",
      description: "View prayer requests",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Submit Prayer Request",
      slug: "submit-prayer-request",
      action: "create",
      description: "Submit prayer request",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Assign Prayer Request",
      slug: "assign-prayer-request",
      action: "update",
      description: "Assign prayer requests",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Mark Prayer Answered",
      slug: "mark-prayer-answered",
      action: "update",
      description: "Mark prayer as answered",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "View Private Prayers",
      slug: "view-private-prayers",
      action: "read",
      description: "View private prayer requests",
    },
    // Prayer Warriors
    {
      moduleId: moduleMap["Ministry"],
      name: "View Prayer Warriors",
      slug: "view-prayer-warriors",
      action: "read",
      description: "View prayer warriors",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Add Prayer Warrior",
      slug: "add-prayer-warrior",
      action: "create",
      description: "Add prayer warrior",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Manage Prayer Assignments",
      slug: "manage-prayer-assignments",
      action: "manage",
      description: "Manage prayer assignments",
    },
    // Training and Certification
    {
      moduleId: moduleMap["Ministry"],
      name: "View Training Courses",
      slug: "view-training-courses",
      action: "read",
      description: "View training courses",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Create Training Course",
      slug: "create-training-course",
      action: "create",
      description: "Create new course",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Edit Training Course",
      slug: "edit-training-course",
      action: "update",
      description: "Edit course content",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Delete Training Course",
      slug: "delete-training-course",
      action: "delete",
      description: "Delete course",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Manage Course Enrollment",
      slug: "manage-course-enrollment",
      action: "manage",
      description: "Manage course enrollment",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Issue Certificate",
      slug: "issue-certificate",
      action: "create",
      description: "Issue certificates",
    },
    // Training Compliance
    {
      moduleId: moduleMap["Ministry"],
      name: "View Training Compliance",
      slug: "view-training-compliance",
      action: "read",
      description: "View compliance status",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Send Training Reminders",
      slug: "send-training-reminders",
      action: "create",
      description: "Send compliance reminders",
    },
    {
      moduleId: moduleMap["Ministry"],
      name: "Manage Mandatory Training",
      slug: "manage-mandatory-training",
      action: "manage",
      description: "Manage mandatory training",
    },

    // ============================================
    // FINANCE PERMISSIONS
    // ============================================
    // Digital Giving
    {
      moduleId: moduleMap["Finance"],
      name: "View Digital Giving",
      slug: "view-digital-giving",
      action: "read",
      description: "View digital giving",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Process Donation",
      slug: "process-donation",
      action: "create",
      description: "Process donations",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Manage Giving Campaigns",
      slug: "manage-giving-campaigns",
      action: "manage",
      description: "Manage giving campaigns",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Export Giving Transactions",
      slug: "export-giving-transactions",
      action: "export",
      description: "Export transactions",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "View Giving Analytics",
      slug: "view-giving-analytics",
      action: "read",
      description: "View giving analytics",
    },
    // Recurring Giving
    {
      moduleId: moduleMap["Finance"],
      name: "View Recurring Giving",
      slug: "view-recurring-giving",
      action: "read",
      description: "View recurring donations",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Create Recurring Schedule",
      slug: "create-recurring-schedule",
      action: "create",
      description: "Create recurring schedule",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Edit Recurring Schedule",
      slug: "edit-recurring-schedule",
      action: "update",
      description: "Edit recurring schedule",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Pause Recurring Schedule",
      slug: "pause-recurring-schedule",
      action: "update",
      description: "Pause/resume schedule",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Cancel Recurring Schedule",
      slug: "cancel-recurring-schedule",
      action: "delete",
      description: "Cancel recurring donation",
    },
    // Pledges
    {
      moduleId: moduleMap["Finance"],
      name: "View Pledges",
      slug: "view-pledges",
      action: "read",
      description: "View pledges",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Create Pledge",
      slug: "create-pledge",
      action: "create",
      description: "Create new pledge",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Record Pledge Payment",
      slug: "record-pledge-payment",
      action: "create",
      description: "Record pledge payment",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Send Pledge Reminder",
      slug: "send-pledge-reminder",
      action: "create",
      description: "Send pledge reminders",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "View Pledge History",
      slug: "view-pledge-history",
      action: "read",
      description: "View pledge history",
    },
    // Tax Receipts
    {
      moduleId: moduleMap["Finance"],
      name: "View Tax Receipts",
      slug: "view-tax-receipts",
      action: "read",
      description: "View tax receipts",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Generate Tax Receipts",
      slug: "generate-tax-receipts",
      action: "create",
      description: "Generate tax receipts",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Export Tax Receipts",
      slug: "export-tax-receipts",
      action: "export",
      description: "Export tax receipts",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Send Tax Receipts",
      slug: "send-tax-receipts",
      action: "create",
      description: "Send receipts to donors",
    },
    // Funds
    {
      moduleId: moduleMap["Finance"],
      name: "View Funds",
      slug: "view-funds",
      action: "read",
      description: "View funds",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Create Fund",
      slug: "create-fund",
      action: "create",
      description: "Create new fund",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Edit Fund",
      slug: "edit-fund",
      action: "update",
      description: "Edit fund details",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Transfer Funds",
      slug: "transfer-funds",
      action: "update",
      description: "Transfer between funds",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Close Fund",
      slug: "close-fund",
      action: "delete",
      description: "Close fund",
    },
    // Budget and Expenses
    {
      moduleId: moduleMap["Finance"],
      name: "View Budget",
      slug: "view-budget",
      action: "read",
      description: "View budget",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Create Budget",
      slug: "create-budget",
      action: "create",
      description: "Create budget",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Edit Budget",
      slug: "edit-budget",
      action: "update",
      description: "Edit budget",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Export Budget",
      slug: "export-budget",
      action: "export",
      description: "Export budget reports",
    },
    // Expense Management
    {
      moduleId: moduleMap["Finance"],
      name: "View Expenses",
      slug: "view-expenses",
      action: "read",
      description: "View expenses",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Submit Expense",
      slug: "submit-expense",
      action: "create",
      description: "Submit expense report",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Approve Expense",
      slug: "approve-expense",
      action: "approve",
      description: "Approve expense reports",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Reject Expense",
      slug: "reject-expense",
      action: "reject",
      description: "Reject expense reports",
    },
    {
      moduleId: moduleMap["Finance"],
      name: "Escalate Expense",
      slug: "escalate-expense",
      action: "update",
      description: "Escalate expense for review",
    },

    // ============================================
    // PAYROLL PERMISSIONS
    // ============================================
    {
      moduleId: moduleMap["Payroll"],
      name: "View Payroll",
      slug: "view-payroll",
      action: "read",
      description: "View payroll overview",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Setup Payroll",
      slug: "setup-payroll",
      action: "manage",
      description: "Configure payroll settings",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "View Payroll History",
      slug: "view-payroll-history",
      action: "read",
      description: "View payroll history",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Export Payslips",
      slug: "export-payslips",
      action: "export",
      description: "Export payslips",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Manage Statutory Compliance",
      slug: "manage-statutory-compliance",
      action: "manage",
      description: "Manage statutory compliance (PAYE, Pension, NHF)",
    },
    // Payroll Employees
    {
      moduleId: moduleMap["Payroll"],
      name: "View Payroll Employees",
      slug: "view-payroll-employees",
      action: "read",
      description: "View payroll employees",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Add Payroll Employee",
      slug: "add-payroll-employee",
      action: "create",
      description: "Add employee to payroll",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Edit Employee Salary",
      slug: "edit-employee-salary",
      action: "update",
      description: "Edit employee salary",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Manage Employee Bank Details",
      slug: "manage-employee-bank-details",
      action: "manage",
      description: "Manage bank details",
    },
    // Run Payroll
    {
      moduleId: moduleMap["Payroll"],
      name: "Run Payroll",
      slug: "run-payroll",
      action: "create",
      description: "Process monthly payroll",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Preview Payroll",
      slug: "preview-payroll",
      action: "read",
      description: "Preview payroll calculation",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Approve Payroll Run",
      slug: "approve-payroll-run",
      action: "approve",
      description: "Approve payroll run",
    },
    // Payroll Calendar
    {
      moduleId: moduleMap["Payroll"],
      name: "View Payroll Calendar",
      slug: "view-payroll-calendar",
      action: "read",
      description: "View payroll calendar",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Create Payroll Calendar",
      slug: "create-payroll-calendar",
      action: "create",
      description: "Create payroll calendar",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Edit Payroll Schedule",
      slug: "edit-payroll-schedule",
      action: "update",
      description: "Edit payroll schedule",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Export Payroll Schedule",
      slug: "export-payroll-schedule",
      action: "export",
      description: "Export schedule",
    },
    // Payroll Approval
    {
      moduleId: moduleMap["Payroll"],
      name: "View Pending Payroll",
      slug: "view-pending-payroll",
      action: "read",
      description: "View pending approvals",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Approve Payroll",
      slug: "approve-payroll",
      action: "approve",
      description: "Approve payroll",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Reject Payroll",
      slug: "reject-payroll",
      action: "reject",
      description: "Reject payroll",
    },
    // Payroll Year-End
    {
      moduleId: moduleMap["Payroll"],
      name: "View Year-End Summary",
      slug: "view-year-end-summary",
      action: "read",
      description: "View year-end summary",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Generate Tax Forms",
      slug: "generate-tax-forms",
      action: "create",
      description: "Generate tax forms",
    },
    {
      moduleId: moduleMap["Payroll"],
      name: "Process Year-End Adjustments",
      slug: "process-year-end-adjustments",
      action: "manage",
      description: "Process year-end adjustments",
    },

    // ============================================
    // ACCOUNTING PERMISSIONS
    // ============================================
    // Chart of Accounts
    {
      moduleId: moduleMap["Accounting"],
      name: "View Chart of Accounts",
      slug: "view-chart-of-accounts",
      action: "read",
      description: "View chart of accounts",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Add Account",
      slug: "add-account",
      action: "create",
      description: "Add new account",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Edit Account",
      slug: "edit-account",
      action: "update",
      description: "Edit account",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Deactivate Account",
      slug: "deactivate-account",
      action: "delete",
      description: "Deactivate account",
    },
    // Journal Entries
    {
      moduleId: moduleMap["Accounting"],
      name: "View Journal Entries",
      slug: "view-journal-entries",
      action: "read",
      description: "View journal entries",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Create Journal Entry",
      slug: "create-journal-entry",
      action: "create",
      description: "Create journal entry",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Edit Draft Entry",
      slug: "edit-draft-entry",
      action: "update",
      description: "Edit draft entries",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Post Journal Entry",
      slug: "post-journal-entry",
      action: "update",
      description: "Post journal entry",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Reverse Journal Entry",
      slug: "reverse-journal-entry",
      action: "update",
      description: "Reverse posted entry",
    },
    // General Ledger
    {
      moduleId: moduleMap["Accounting"],
      name: "View General Ledger",
      slug: "view-general-ledger",
      action: "read",
      description: "View general ledger",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Export General Ledger",
      slug: "export-general-ledger",
      action: "export",
      description: "Export ledger",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Filter Ledger Transactions",
      slug: "filter-ledger-transactions",
      action: "read",
      description: "Filter ledger transactions",
    },
    // Financial Statements
    {
      moduleId: moduleMap["Accounting"],
      name: "View Financial Statements",
      slug: "view-financial-statements",
      action: "read",
      description: "View financial statements",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Generate Income Statement",
      slug: "generate-income-statement",
      action: "create",
      description: "Generate income statement",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Generate Balance Sheet",
      slug: "generate-balance-sheet",
      action: "create",
      description: "Generate balance sheet",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Generate Cash Flow",
      slug: "generate-cash-flow",
      action: "create",
      description: "Generate cash flow statement",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Generate Trial Balance",
      slug: "generate-trial-balance",
      action: "create",
      description: "Generate trial balance",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Export Financial Statements",
      slug: "export-financial-statements",
      action: "export",
      description: "Export statements to PDF",
    },
    // Fiscal Periods
    {
      moduleId: moduleMap["Accounting"],
      name: "View Fiscal Periods",
      slug: "view-fiscal-periods",
      action: "read",
      description: "View fiscal periods",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Create Fiscal Period",
      slug: "create-fiscal-period",
      action: "create",
      description: "Create fiscal period",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Close Fiscal Period",
      slug: "close-fiscal-period",
      action: "update",
      description: "Close fiscal period",
    },
    {
      moduleId: moduleMap["Accounting"],
      name: "Reopen Fiscal Period",
      slug: "reopen-fiscal-period",
      action: "update",
      description: "Reopen closed period",
    },

    // ============================================
    // BANKING PERMISSIONS
    // ============================================
    // Member Banking
    {
      moduleId: moduleMap["Banking"],
      name: "View Member Banking",
      slug: "view-member-banking",
      action: "read",
      description: "View member banking",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Create Member Account",
      slug: "create-member-account",
      action: "create",
      description: "Create member account",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Manage Bank Cards",
      slug: "manage-bank-cards",
      action: "manage",
      description: "Manage bank cards",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "View Member Transactions",
      slug: "view-member-transactions",
      action: "read",
      description: "View member transactions",
    },
    // Banking and Treasury
    {
      moduleId: moduleMap["Banking"],
      name: "View Treasury",
      slug: "view-treasury",
      action: "read",
      description: "View treasury overview",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Link External Accounts",
      slug: "link-external-accounts",
      action: "create",
      description: "Link external accounts",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Request Bank Statement",
      slug: "request-bank-statement",
      action: "create",
      description: "Request bank statement",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Manage Direct Debit",
      slug: "manage-direct-debit",
      action: "manage",
      description: "Manage direct debit",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Sync Account Balances",
      slug: "sync-account-balances",
      action: "update",
      description: "Sync account balances",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "View Financial Audit Log",
      slug: "view-financial-audit-log",
      action: "read",
      description: "View financial audit log",
    },
    // Bank Accounts
    {
      moduleId: moduleMap["Banking"],
      name: "View Bank Accounts",
      slug: "view-bank-accounts",
      action: "read",
      description: "View bank accounts",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Create Bank Account",
      slug: "create-bank-account",
      action: "create",
      description: "Create bank account",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Reconcile Account",
      slug: "reconcile-account",
      action: "update",
      description: "Reconcile accounts",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Connect Bank API",
      slug: "connect-bank-api",
      action: "manage",
      description: "Connect bank API",
    },
    // Lending and Credit
    {
      moduleId: moduleMap["Banking"],
      name: "View Member Loans",
      slug: "view-member-loans",
      action: "read",
      description: "View member loans",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Create Loan Application",
      slug: "create-loan-application",
      action: "create",
      description: "Create loan application",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Approve Loan",
      slug: "approve-loan",
      action: "approve",
      description: "Approve loan",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Disburse Loan",
      slug: "disburse-loan",
      action: "update",
      description: "Disburse loan",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Record Loan Payment",
      slug: "record-loan-payment",
      action: "create",
      description: "Record loan payment",
    },
    // Church Loans
    {
      moduleId: moduleMap["Banking"],
      name: "View Church Loans",
      slug: "view-church-loans",
      action: "read",
      description: "View church loans",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Apply for Church Loan",
      slug: "apply-for-church-loan",
      action: "create",
      description: "Apply for institutional loan",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Manage Partner Institutions",
      slug: "manage-partner-institutions",
      action: "manage",
      description: "Manage partner institutions",
    },
    {
      moduleId: moduleMap["Banking"],
      name: "Make Church Loan Payment",
      slug: "make-church-loan-payment",
      action: "create",
      description: "Make loan payment",
    },

    // ============================================
    // REMITTANCE PERMISSIONS
    // ============================================
    {
      moduleId: moduleMap["Remittance"],
      name: "View Remittances",
      slug: "view-remittances",
      action: "read",
      description: "View all remittances",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "View Missionary Support",
      slug: "view-missionary-support",
      action: "read",
      description: "View missionary support",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "View Transfer History",
      slug: "view-transfer-history",
      action: "read",
      description: "View transfer history",
    },
    // Send Money
    {
      moduleId: moduleMap["Remittance"],
      name: "Send Remittance",
      slug: "send-remittance",
      action: "create",
      description: "Send cross-border remittance",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "Send to Missionary",
      slug: "send-to-missionary",
      action: "create",
      description: "Send to missionary",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "Submit Transfer for Approval",
      slug: "submit-transfer-for-approval",
      action: "create",
      description: "Submit transfer for approval",
    },
    // Compliance and KYC/AML
    {
      moduleId: moduleMap["Remittance"],
      name: "View Compliance Status",
      slug: "view-compliance-status",
      action: "read",
      description: "View compliance status",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "Review Flagged Transactions",
      slug: "review-flagged-transactions",
      action: "read",
      description: "Review flagged transactions",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "Approve Transfer",
      slug: "approve-transfer",
      action: "approve",
      description: "Approve transfers",
    },
    {
      moduleId: moduleMap["Remittance"],
      name: "Flag Transaction",
      slug: "flag-transaction",
      action: "update",
      description: "Flag suspicious activity",
    },

    // ============================================
    // RESOURCES PERMISSIONS
    // ============================================
    // Facilities
    {
      moduleId: moduleMap["Resources"],
      name: "View Facilities",
      slug: "view-facilities",
      action: "read",
      description: "View facilities",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Add Facility",
      slug: "add-facility",
      action: "create",
      description: "Add new facility",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Edit Facility",
      slug: "edit-facility",
      action: "update",
      description: "Edit facility",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Book Facility",
      slug: "book-facility",
      action: "create",
      description: "Book facility",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "View Facility Schedule",
      slug: "view-facility-schedule",
      action: "read",
      description: "View facility schedule",
    },
    // Assets
    {
      moduleId: moduleMap["Resources"],
      name: "View Assets",
      slug: "view-assets",
      action: "read",
      description: "View assets",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Add Asset",
      slug: "add-asset",
      action: "create",
      description: "Add new asset",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Edit Asset",
      slug: "edit-asset",
      action: "update",
      description: "Edit asset",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Manage Depreciation",
      slug: "manage-depreciation",
      action: "manage",
      description: "Manage depreciation",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Schedule Maintenance",
      slug: "schedule-maintenance",
      action: "create",
      description: "Schedule maintenance",
    },
    // Procurement
    {
      moduleId: moduleMap["Resources"],
      name: "View Procurement",
      slug: "view-procurement",
      action: "read",
      description: "View procurement requests",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Create Purchase Request",
      slug: "create-purchase-request",
      action: "create",
      description: "Create purchase request",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Approve Purchase Request",
      slug: "approve-purchase-request",
      action: "approve",
      description: "Approve purchase request",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Reject Purchase Request",
      slug: "reject-purchase-request",
      action: "reject",
      description: "Reject purchase request",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Mark as Ordered",
      slug: "mark-as-ordered",
      action: "update",
      description: "Mark as ordered",
    },
    // Media and Streaming
    {
      moduleId: moduleMap["Resources"],
      name: "View Media Library",
      slug: "view-media-library",
      action: "read",
      description: "View media library",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Upload Media",
      slug: "upload-media",
      action: "create",
      description: "Upload media content",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Start Livestream",
      slug: "start-livestream",
      action: "create",
      description: "Start live stream",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Manage Sermon Archives",
      slug: "manage-sermon-archives",
      action: "manage",
      description: "Manage sermon archives",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Configure Streaming Platforms",
      slug: "configure-streaming-platforms",
      action: "manage",
      description: "Configure streaming platforms",
    },
    // Documents
    {
      moduleId: moduleMap["Resources"],
      name: "View Documents",
      slug: "view-documents",
      action: "read",
      description: "View documents",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Upload Document",
      slug: "upload-document",
      action: "create",
      description: "Upload document",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Manage Compliance Documents",
      slug: "manage-compliance-documents",
      action: "manage",
      description: "Manage compliance documents",
    },
    {
      moduleId: moduleMap["Resources"],
      name: "Download Document",
      slug: "download-document",
      action: "read",
      description: "Download documents",
    },

    // ============================================
    // CAMPUSES PERMISSIONS
    // ============================================
    {
      moduleId: moduleMap["Campuses"],
      name: "View Campuses",
      slug: "view-campuses",
      action: "read",
      description: "View all campuses",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "Add Campus",
      slug: "add-campus",
      action: "create",
      description: "Add new campus",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "Edit Campus",
      slug: "edit-campus",
      action: "update",
      description: "Edit campus details",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "Manage Campus Operations",
      slug: "manage-campus-operations",
      action: "manage",
      description: "Manage campus operations",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "View Campus Analytics",
      slug: "view-campus-analytics",
      action: "read",
      description: "View campus analytics",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "Manage Inter-Campus Remittances",
      slug: "manage-inter-campus-remittances",
      action: "manage",
      description: "Manage inter-campus remittances",
    },
    // Campus Benchmarking
    {
      moduleId: moduleMap["Campuses"],
      name: "View Campus Benchmarks",
      slug: "view-campus-benchmarks",
      action: "read",
      description: "View campus benchmarks",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "Compare Campus Metrics",
      slug: "compare-campus-metrics",
      action: "read",
      description: "Compare campus metrics",
    },
    {
      moduleId: moduleMap["Campuses"],
      name: "Export Campus Comparison",
      slug: "export-campus-comparison",
      action: "export",
      description: "Export comparison reports",
    },

    // ============================================
    // SETTINGS PERMISSIONS
    // ============================================
    // Organization Settings
    {
      moduleId: moduleMap["Settings"],
      name: "View Organization Settings",
      slug: "view-organization-settings",
      action: "read",
      description: "View organization settings",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Edit Organization Info",
      slug: "edit-organization-info",
      action: "update",
      description: "Edit organization info",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Manage Branding",
      slug: "manage-branding",
      action: "manage",
      description: "Manage branding and theme",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Configure Multi-Campus",
      slug: "configure-multi-campus",
      action: "manage",
      description: "Configure multi-campus settings",
    },
    // Users and Roles Management
    {
      moduleId: moduleMap["Settings"],
      name: "View Users",
      slug: "view-users",
      action: "read",
      description: "View users",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Manage Users",
      slug: "manage-users",
      action: "manage",
      description: "Manage users",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "View Roles",
      slug: "view-roles",
      action: "read",
      description: "View roles",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Create Custom Role",
      slug: "create-custom-role",
      action: "create",
      description: "Create custom role",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Edit Role Permissions",
      slug: "edit-role-permissions",
      action: "update",
      description: "Edit role permissions",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Delete Custom Role",
      slug: "delete-custom-role",
      action: "delete",
      description: "Delete custom role",
    },
    {
      moduleId: moduleMap["Settings"],
      name: "Assign Roles",
      slug: "assign-roles",
      action: "update",
      description: "Assign roles to users",
    },
  ]);
}